//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUR.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEntities : DbContext

    {
        private static BDEntities _context;


        public BDEntities()
            : base("name=BDEntities")
        {
        }

        public static BDEntities GetContext()
        {
            if (_context == null)
                _context = new BDEntities();
            return _context;

        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientTable> ClientTable { get; set; }
        public virtual DbSet<OrderTable> OrderTable { get; set; }
        public virtual DbSet<PointTable> PointTable { get; set; }
        public virtual DbSet<ProductPaymentStatusTable> ProductPaymentStatusTable { get; set; }
        public virtual DbSet<ProductStatusTable> ProductStatusTable { get; set; }
        public virtual DbSet<ProductTable> ProductTable { get; set; }
        public virtual DbSet<SupplierTable> SupplierTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeProductTable> TypeProductTable { get; set; }
        public virtual DbSet<WarehouseTable> WarehouseTable { get; set; }
    }
}
