//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int id_order { get; set; }
        public Nullable<int> id_product_payment_status { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_product_status { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_point { get; set; }
        public Nullable<System.DateTime> product_units { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<int> shelf_life { get; set; }
    
        public virtual ClientTable ClientTable { get; set; }
        public virtual PointTable PointTable { get; set; }
        public virtual ProductPaymentStatusTable ProductPaymentStatusTable { get; set; }
        public virtual ProductStatusTable ProductStatusTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
